// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mtur_api.Context;

#nullable disable

namespace Mtur_api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110175051_terceiroBd")]
    partial class terceiroBd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mtur_api.Models.Cliente", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("cpf");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Mtur_api.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("assunto")
                        .HasColumnType("longtext");

                    b.Property<string>("mensagem")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("Mtur_api.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<double>("preco")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("Mtur_api.Models.Reserva", b =>
                {
                    b.Property<int>("numeroReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("formaPagamento")
                        .HasColumnType("longtext");

                    b.Property<double>("valorReserva")
                        .HasColumnType("double");

                    b.HasKey("numeroReserva");

                    b.ToTable("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
